sudo: required

services:
  - docker

language: node_js

node_js:
  - "node"

install: true

script:
  - sh .travis/configure-tag.sh
  - docker build -t $CONTAINER_NAME:$TAG .
  - docker run $CONTAINER_NAME:$TAG npm test -- -i --no-cache

after_success:
  - docker run $CONTAINER_NAME:$TAG cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - sh .travis/deploy.sh
