sudo: required

services:
  - docker

language: node_js

# cache: yarn

node_js:
  - "node"

install: true

script:
  # - npm test -- -i --no-cache
  - echo "no tests"

after_success:
  # - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  # - sh .travis/deploy-dockerhub.sh
  # - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy-heroku.sh
  - sh .travis/deploy-ecs.sh
