sudo: required

services:
  - docker

language: node_js

cache: yarn

node_js:
  - "node"

script:
  - npm test -- -i --no-cache

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - sh .travis/deploy-ecr.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy-heroku.sh
